// @generated by linkrpc::schema::codegen from an endpoint contract.
// Do not edit by hand; regenerate from the contract instead.
#![cfg_attr(rustfmt, rustfmt::skip)]
pub mod types;
pub mod mod_2;
pub mod self_;
pub mod self_2;
pub mod r#type;
pub mod type_2;
pub mod type_2_2;
pub mod types_2;
