// @generated by linkrpc::schema::codegen from interface `mod`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"mod\",\"hash\":\"32749adc3cbdee64\",\"description\":\"index collision\",\"methods\":{\"echo\":{\"params\":{\"type\":\"string\"},\"result\":{\"type\":\"string\"}}}}",
    omit_optional_params = true,
    client = "ModClient",
    server = "ModServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
/// index collision
pub trait ModService {
    #[name("echo")]
    async fn echo(#[params] params: String) -> Result<String, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, params,);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "echo"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
