// @generated by linkrpc::schema::codegen from interface `self`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"self\",\"hash\":\"cb9496d7e72c9068\",\"description\":\"non-raw keyword\",\"methods\":{\"echo\":{\"params\":{\"type\":\"string\"},\"result\":{\"type\":\"string\"}}}}",
    client = "Self_Client",
    server = "Self_Server",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
/// non-raw keyword
pub trait Self_Service {
    #[name("echo")]
    async fn echo(#[params] params: String) -> Result<String, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, params);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "echo"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
