// @generated by linkrpc::schema::codegen from interface `type`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"type\",\"hash\":\"574356f7ef59552d\",\"description\":\"first version\",\"methods\":{\"echo\":{\"params\":{\"type\":\"string\"},\"result\":{\"type\":\"string\"}}}}",
    omit_optional_params = true,
    client = "TypeClient",
    server = "TypeServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
/// first version
pub trait TypeService {
    #[name("echo")]
    async fn echo(#[params] params: String) -> Result<String, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, params,);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "echo"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
