// @generated by linkrpc::schema::codegen from interface `types`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"types\",\"hash\":\"e2c8f70c1b84fcbd\",\"description\":\"common types collision\",\"methods\":{\"echo\":{\"params\":{\"type\":\"string\"},\"result\":{\"type\":\"string\"}}}}",
    client = "TypesClient",
    server = "TypesServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
/// common types collision
pub trait TypesService {
    #[name("echo")]
    async fn echo(#[params] params: String) -> Result<String, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, params);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "echo"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
