/**
 * Emit shell-completion scripts. Currently PowerShell only; the entry point
 * is structured so adding bash / zsh later just plugs in another renderer.
 *
 * The scripts shell out to `hub _complete --line <line> --point <cursor>`,
 * which prints one candidate per line in the format `text\ttooltip`. PS
 * turns each line into a `CompletionResult`.
 */

export type SupportedShell = 'powershell';

const SUPPORTED: ReadonlySet<SupportedShell> = new Set(['powershell']);

export function isSupportedShell(name: string): name is SupportedShell {
    return SUPPORTED.has(name as SupportedShell);
}

export function emitCompletionScript(shell: SupportedShell): string {
    if (shell === 'powershell') return POWERSHELL_SCRIPT;
    throw new Error(`unsupported shell: ${shell}`);
}

/**
 * The PowerShell registration script. Self-contained — `Invoke-Expression`
 * of this string registers a native completer for `hub`, `linkrpc`, and `rpc`.
 *
 * Notes:
 *   - `$commandAst.Extent.Text` is the entire pipeline element text (the
 *     part PS treats as one command); `$cursorPosition` is absolute, so we
 *     subtract `$commandAst.Extent.StartOffset` to get a position relative
 *     to the line we're handing to the CLI.
 *   - We invoke whichever binary the user is actually typing
 *     (`$commandAst.CommandElements[0]`) so a local `hub.exe` and a global
 *     one both work transparently.
 *   - All errors are silently swallowed — a broken completer must never
 *     break the user's prompt.
 */
const POWERSHELL_SCRIPT = `
# linkrpc completion for PowerShell — auto-generated by \`hub completions powershell\`.
# Install once with:  hub completions powershell | Out-String | Invoke-Expression
# Persist with:       hub completions powershell >> $PROFILE
Register-ArgumentCompleter -Native -CommandName hub,linkrpc,rpc -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    try {
        $line  = $commandAst.Extent.Text
        $point = $cursorPosition - $commandAst.Extent.StartOffset
        if ($point -lt 0) { $point = 0 }
        if ($point -gt $line.Length) { $point = $line.Length }

        $binElement = $commandAst.CommandElements[0]
        $bin = if ($binElement.Value) { $binElement.Value } else { $binElement.Extent.Text }

        # The completer must never write to the user's prompt. Redirect stderr.
        $raw = & $bin _complete --line $line --point $point 2>$null
        if (-not $raw) { return }

        foreach ($entry in ($raw -split "\`r?\`n")) {
            if (-not $entry) { continue }
            $parts = $entry -split "\`t", 2
            $text    = $parts[0]
            $tooltip = if ($parts.Length -ge 2 -and $parts[1]) { $parts[1] } else { $text }
            [System.Management.Automation.CompletionResult]::new(
                $text,
                $text,
                [System.Management.Automation.CompletionResultType]::ParameterValue,
                $tooltip
            )
        }
    } catch {
        # Silent: a broken completer must not break the prompt.
    }
}
`.trimStart();
