import { randomUUID } from 'node:crypto';
import { ErrorCode, isNotification, isRequest, isResponse, RpcError, TransportPair } from '@hediet/linkrpc';
import type { IMessageTransport, JsonRpcMessage, JsonRpcRequest, JsonRpcResponse, RequestId } from '@hediet/linkrpc';
import type { JsonValue } from '@hediet/linkrpc';
import { parseMethodName } from '@hediet/linkrpc';
import type { NodeTransit, NodeTransitObserver, TransitEndpoint, TransitError } from '../nodeTransit';
import {
    STREAM_METHOD,
    StreamControlReason,
    StreamControlType,
    StreamDir,
    type StreamSendParams,
} from '@hediet/linkrpc';
import { ForwardingTable, validatePrefix } from './forwardingTable';
import {
    type NodeInfo,
    type ParticipantDescriptorSource,
    type ServiceId,
    type TopologyGraph,
    type TopologyTransportInfo,
} from '@hediet/linkrpc/hub/common';
import {
    isInspectionLifecycle,
    isReservedInspectionInterface,
    markInspectionLifecycle,
} from '../inspectionLifecycle';
import { ParticipantRoots } from './participantRoots';
import {
    GET_NODE_ID_METHOD,
    RoutingTopology,
    type ManagedRoutingTopology,
    type ManagedTopologyFragment,
} from './routingTopology';

export type { ManagedRoutingTopology, ManagedTopologyFragment } from './routingTopology';

/** A forwarded request awaiting its response, keyed by the hub's rewritten id. */
interface PendingForward {
    /** Link the original request arrived on; the response is returned here. */
    readonly origin: IMessageTransport;
    /** Id the origin used; restored onto the response before returning it. */
    readonly originalId: RequestId;
    /** Fully-qualified method, for {@link Hub.pendingRequests} diagnostics. */
    readonly method: string;
    /** When the request was forwarded (ms), for in-flight age reporting. */
    readonly startedAtMs: number;
    /**
     * Link the request was forwarded to. The response is only accepted from
     * this exact link, so a downstream cannot forge a reply (with a guessed
     * sequential id) to a request that was actually routed elsewhere.
     */
    readonly target: IMessageTransport;
    /** Suppress observation for the trusted inspection call's whole lifecycle. */
    readonly inspection: boolean;
    /**
     * Idle-timeout handle. Armed when the request is forwarded, reset on
     * every stream message (incl. keepalive pings), and cleared when the
     * entry is deleted. Bounds `_pending` so a target that never replies
     * (and a caller that never pings) cannot leak an entry forever — which
     * is also the hub's slow-loris / DDoS backstop.
     */
    timer?: ReturnType<typeof setTimeout>;
}

/**
 * How a method name resolves against this hub's routing state. The
 * structural invariant lives here: root-addressed calls (`bare`/`interface`
 * form) can only ever resolve to loopback — they are **never**
 * forwarded to a prefix owner or the uplink.
 */
type Resolution =
    | { readonly kind: 'malformed'; }
    | { readonly kind: 'loopback'; readonly link: IMessageTransport | undefined; }
    | { readonly kind: 'prefix'; readonly link: IMessageTransport; readonly prefix: ServiceId; }
    | { readonly kind: 'uplink'; readonly link: IMessageTransport | undefined; };

/**
 * Diagnostics sink for a {@link Hub}. Deliberately structurally compatible
 * with VS Code's `LogOutputChannel`, so an extension can pass its log channel
 * straight in without an adapter.
 *
 * The hub only ever logs *routing decisions* — method names, the resolution
 * kind, claimed prefixes and error reasons — never message **payloads**
 * (params/results), so attaching a logger never leaks call arguments.
 */
export interface IHubLogger {
    trace(message: string): void;
    debug(message: string): void;
    info(message: string): void;
    warn(message: string): void;
    error(message: string): void;
}

export interface HubOptions {
    /** Name used in error payloads / diagnostics. */
    readonly debugName?: string;
    /** Optional diagnostic descriptor for this routing node. */
    readonly descriptors?: readonly ParticipantDescriptorSource[];
    /** Stable topology identity for this hub. A random id is generated by default. */
    readonly nodeId?: string;
    /**
     * Optional diagnostics sink. When omitted the hub logs nothing and pays no
     * string-formatting cost (log calls short-circuit on the missing logger).
     */
    readonly logger?: IHubLogger;
    /**
     * Per-request idle timeout in milliseconds. A forwarded request whose
     * stream is idle for this long (no response, no stream message, no
     * keepalive ping) is cancelled toward its target and failed back to its
     * origin with a `requestTimeout` error. Defaults to 30 minutes. Set to
     * `0` (or a negative value) to disable — only sensible in tests, since
     * it removes the hub's bound on `_pending` growth.
     */
    readonly idleTimeoutMs?: number;
    /** Best-effort timeout for topology peer identification. */
    readonly peerIdentificationTimeoutMs?: number;
    /**
     * Optional initial node-transit observer. Additional observers can be
     * attached dynamically with {@link Hub.observeTransits}. When set, the hub emits a
     * {@link NodeTransit} for every message it routes (requests, responses,
     * notifications, stream frames). Off by default — when omitted the emit
     * sites short-circuit and allocate nothing. Never carries more than the
     * method/params/result the hub already handles.
     */
    readonly onTransit?: NodeTransitObserver;
    /**
     * Gate for emitting `kind:'stream'` transits to transit observers. Stream
     * frames (`$stream::send` — app stdout/stderr payloads plus cancel/ping/pong
     * controls) are high-frequency, so they are **off by default**: when this is
     * absent or returns `false`, stream routing allocates no transit (only
     * request/response/notification frames are observed). Wire it to a verbosity
     * check (e.g. log level ≥ debug) to fold per-frame stream detail into the
     * owning request's flow. Evaluated per frame, so it tracks live level
     * changes.
     */
    readonly emitStreamTransits?: () => boolean;
}

const DEFAULT_IDLE_TIMEOUT_MS = 30 * 60_000;

/** Minimal disposable handle; calling `dispose` detaches the link. */
export interface IDisposable {
    dispose(): void;
}

/** A snapshot row from {@link Hub.pendingRequests}: one in-flight forward. */
export interface PendingRequestInfo {
    /** Hub-rewritten id the target sees. */
    readonly hubId: string;
    /** Original id the origin used. */
    readonly originalId: RequestId;
    /** Fully-qualified method. */
    readonly method: string;
    /** Edge the request arrived on. */
    readonly originEdgeId: string;
    /** Edge the request was forwarded to. */
    readonly targetEdgeId: string;
    /** Milliseconds the request has been in flight. */
    readonly ageMs: number;
}

/**
 * Handle returned by {@link Hub.attach}. Beyond detaching the link, it lets
 * the caller claim/release prefixes *bound to this specific link* without
 * holding a reference to the link itself — the seam a {@link RootOverlay}
 * uses to let its root services claim upstream on the participant's behalf.
 */
export interface AttachedLink extends IDisposable {
    /** Bind `prefix` to this link (see {@link Hub.claimPrefix}). */
    claimPrefix(prefix: ServiceId): void;
    /** Release `prefix` from the table. Returns `true` if it existed. */
    releasePrefix(prefix: ServiceId): boolean;
    /**
     * The stable inspection id the hub uses for this link in its
     * {@link NodeTransit} events. A neighbouring node (e.g. an
     * {@link import('./overlaySplitter').OverlaySplitter}) should label the
     * *same physical edge* with this id so a {@link TransitAggregator} chains
     * the two nodes' transits across the boundary.
     */
    readonly edgeId: string;
    /** Stable topology port identity, independent of the mutable friendly edge label. */
    readonly portId: string;
    /** Identify and cache the node/port at the far end of this exact link. */
    identifyPeer(): Promise<NodeInfo>;
    /** Send a bounded root request to the far end while the Hub owns dispatch. */
    request(method: string, params: JsonValue, timeoutMs?: number): Promise<JsonValue | undefined>;
}

export interface AttachLinkOptions {
    readonly edgeId?: string;
    readonly transport?: TopologyTransportInfo;
}

/**
 * A **Hub** is the entire routing concept of linkrpc v2 — the only noun.
 * It is a tiny message router with an unauthenticated topology-correlation
 * identity and exactly three moving
 * parts, all expressed as {@link IMessageTransport} links:
 *
 * - **forwarding table** — longest-prefix serviceId → link map (the
 *   downstream neighbours / claimed subnets).
 * - **loopback** — an optional link to the local root services (`bare`/
 *   `interface`-form calls land here and *never* leave the hub). This is
 *   the routing equivalent of `127.0.0.1`.
 * - **uplink** — an optional default route. A hub *with* an uplink is also
 *   a participant of its parent hub, which is how hubs **nest** (a VS Code
 *   window hub uplinks to an OS hub uplinks to a home-server hub).
 *
 * Routing is pure longest-prefix forwarding with JSON-RPC id rewriting:
 * a forwarded request keeps its full method name verbatim; only its `id`
 * is swapped for a hub-local one so responses can be demultiplexed back to
 * the originating link. There is no notion of identity, capabilities, or
 * trust at this layer — those are policies layered on top.
 *
 * The single privileged write seam is {@link claimPrefix}; everything else
 * is mechanical message shuffling.
 */
export class Hub {
    /** Unauthenticated topology-correlation identity for this hub. */
    public readonly nodeId: string;

    private readonly _table = new ForwardingTable<IMessageTransport>();
    private readonly _links = new Set<IMessageTransport>();
    private readonly _pending = new Map<string, PendingForward>();

    private _uplink: IMessageTransport | undefined;
    private _loopback: IMessageTransport | undefined;
    private _nextId = 1;

    private readonly _log: IHubLogger | undefined;
    private readonly _transitObservers = new Set<NodeTransitObserver>();

    /**
     * Listeners notified whenever the forwarding table changes (a prefix is
     * claimed or released, or a link detaches dropping its claims). Coarse, by
     * design: it carries no payload — consumers re-query the directory. This is
     * the "poll now" nudge that backs `linkrpc.directory::watch`.
     */
    private readonly _routingListeners = new Set<() => void>();

    /** Stable inspection label per link; assigned lazily / by prefix claim. */
    private readonly _edgeIds = new WeakMap<IMessageTransport, string>();
    private readonly _transportInfo = new WeakMap<IMessageTransport, TopologyTransportInfo>();
    private _nextEdgeId = 1;
    private readonly _topology: RoutingTopology;
    private readonly _participantRoots: ParticipantRoots;

    /** Per-request idle timeout in ms; `<= 0` disables. See {@link HubOptions.idleTimeoutMs}. */
    private readonly _idleMs: number;

    constructor(private readonly _options: HubOptions = {}) {
        this.nodeId = _options.nodeId ?? randomUUID();
        this._log = _options.logger;
        if (_options.onTransit !== undefined) this._transitObservers.add(_options.onTransit);
        this._idleMs = _options.idleTimeoutMs ?? DEFAULT_IDLE_TIMEOUT_MS;
        this._topology = new RoutingTopology({
            nodeId: this.nodeId,
            debugName: _options.debugName,
            descriptors: _options.descriptors,
            peerIdentificationTimeoutMs: _options.peerIdentificationTimeoutMs,
            links: () => this._links,
            forwardingEntries: () => this._table.entries(),
            edgeId: (link) => this._edgeId(link),
            transportInfo: (link) => this._transportInfo.get(link),
            isAttached: (link) => this._links.has(link),
            requestOnLink: (link, method, params, inspection, timeoutMs) =>
                this._requestOnLink(link, method, params, inspection, timeoutMs),
            onDidChange: () => this._fireRoutingChanged(),
        });
        this._participantRoots = new ParticipantRoots({
            forwardingEntries: () => this._table.entries(),
            prefixOwner: (prefix) => this._table.get(prefix),
            uplink: () => this._uplink,
            requestOnLink: (link, method, params) => this._requestOnLink(link, method, params),
            watchOnLink: (link, method, params, onTick, onSettled, onEstablished) =>
                this._watchOnLink(link, method, params, onTick, onSettled, onEstablished),
            onDidChangeRouting: (listener) => this.onDidChangeRouting(listener),
        });
    }

    /** Prefix for log lines; identifies this hub when nested. */
    private _tag(): string {
        return this._options.debugName !== undefined ? `[${this._options.debugName}] ` : '';
    }

    /** Stable inspection label for a link; auto-assigned on first use. */
    private _edgeId(link: IMessageTransport): string {
        let id = this._edgeIds.get(link);
        if (id === undefined) {
            id = `e${this._nextEdgeId++}`;
            this._edgeIds.set(link, id);
        }
        return id;
    }

    /** Give `link` a friendly inspection label (prefix / loopback / uplink). */
    private _labelEdge(link: IMessageTransport, label: string): void {
        const cur = this._edgeIds.get(link);
        // Don't clobber a meaningful label with a later, less specific one.
        if (cur === undefined || /^e\d+$/.test(cur)) this._edgeIds.set(link, label);
    }

    /** Emit a pre-built node transit. Callers guard construction by observer count. */
    private _emit(t: NodeTransit): void {
        for (const observer of [...this._transitObservers]) {
            try {
                observer(t);
            } catch (err) {
                this._log?.warn(`${this._tag()}transit observer threw: ${String(err)}`);
            }
        }
    }

    private _transitEndpoint(
        link: IMessageTransport,
        requestId?: RequestId,
    ): TransitEndpoint {
        return {
            edgeId: this._edgeId(link),
            portId: this._topology.portId(link),
            ...(requestId !== undefined ? { requestId } : {}),
        };
    }

    /** Number of live transit observers. */
    public get transitObserverCount(): number {
        return this._transitObservers.size;
    }

    /** Observe routed messages until the returned handle is disposed. */
    public observeTransits(observer: NodeTransitObserver): IDisposable {
        this._transitObservers.add(observer);
        let disposed = false;
        return {
            dispose: () => {
                if (disposed) return;
                disposed = true;
                this._transitObservers.delete(observer);
            },
        };
    }

    /**
     * Publish a transit from a routing node managed by this Hub. Callers should
     * check {@link transitObserverCount} before constructing the transit.
     */
    public publishManagedTransit(transit: NodeTransit): void {
        if (this._transitObservers.size === 0) return;
        this._emit(transit);
    }

    /** Replace an attached link's direct topology edge with a managed routing node. */
    public registerManagedRoutingTopology(
        attached: AttachedLink,
        topology: ManagedRoutingTopology,
    ): IDisposable {
        return this._topology.registerManagedRoutingTopology(attached, topology);
    }

    /** Add an in-process endpoint or routing fragment to this Hub's topology. */
    public registerManagedTopologyFragment(fragment: ManagedTopologyFragment): IDisposable {
        return this._topology.registerManagedTopologyFragment(fragment);
    }

    /**
     * Subscribe to coarse routing-table changes (prefix claim/release/detach).
     * The listener receives no arguments — it is a "something changed; re-query"
     * nudge. Returns an unsubscribe function.
     */
    public onDidChangeRouting(listener: () => void): () => void {
        this._routingListeners.add(listener);
        return () => {
            this._routingListeners.delete(listener);
        };
    }

    /** Number of active topology/routing invalidation observers. */
    public get routingObserverCount(): number {
        return this._routingListeners.size;
    }

    /** Fire all routing-change listeners. Best-effort; one throwing listener does not block the rest. */
    private _fireRoutingChanged(): void {
        for (const listener of [...this._routingListeners]) {
            try {
                listener();
            } catch (err) {
                this._log?.warn(`${this._tag()}routing-change listener threw: ${String(err)}`);
            }
        }
    }

    /**
     * Emit a `kind:'stream'` transit for a routed `$stream::send` frame, gated by
     * {@link HubOptions.emitStreamTransits}. Stream frames are high-frequency, so
     * the gate is evaluated per frame and — when off — no transit object is
     * built. The endpoints carry the same `(edgeId, requestId)` pairs the owning
     * request used, so the aggregator folds these into that request's flow.
     */
    private _emitStream(note: JsonRpcMessage, inEp: TransitEndpoint, outEp: TransitEndpoint): void {
        if (this._transitObservers.size === 0) return;
        if (this._options.emitStreamTransits?.() !== true) return;
        this._emit({
            ts: Date.now(),
            nodeId: this.nodeId,
            in: inEp,
            out: outEp,
            disposition: 'forwarded',
            kind: 'stream',
            method: STREAM_METHOD,
            params: (note as { params?: JsonValue }).params,
        });
    }

    /**
     * Snapshot the requests currently in flight through this hub. Each row is
     * one {@link _pending} entry — the authoritative in-flight set — annotated
     * with its method, the edges it bridges, and how long it has waited. Useful
     * for surfacing stuck/slow requests in an inspector.
     */
    public pendingRequests(): PendingRequestInfo[] {
        const now = Date.now();
        const out: PendingRequestInfo[] = [];
        for (const [hubId, p] of this._pending) {
            out.push({
                hubId,
                originalId: p.originalId,
                method: p.method,
                originEdgeId: this._edgeId(p.origin),
                targetEdgeId: this._edgeId(p.target),
                ageMs: now - p.startedAtMs,
            });
        }
        return out;
    }

    // -- topology ---------------------------------------------------

    /**
     * Begin routing the messages of `link`. The hub installs itself as the
     * link's listener; do not also attach another listener. Returns a
     * disposable that stops routing the link (detaching the listener and
     * dropping any forwarding entries, uplink/loopback slots, and pending
     * responses bound to it) when disposed.
     */
    public attach(link: IMessageTransport, opts?: AttachLinkOptions): AttachedLink {
        if (opts?.edgeId !== undefined) this._edgeIds.set(link, opts.edgeId);
        if (opts?.transport !== undefined) this._transportInfo.set(link, opts.transport);
        const handle: AttachedLink = {
            dispose: () => this._detach(link),
            claimPrefix: (prefix) => this.claimPrefix(link, prefix),
            releasePrefix: (prefix) => this.releasePrefix(prefix),
            edgeId: this._edgeId(link),
            portId: this._topology.portId(link),
            identifyPeer: () => this._topology.identifyPeer(link),
            request: (method, params, timeoutMs) =>
                this._requestOnLink(link, method, params, false, timeoutMs),
        };
        this._topology.registerHandle(handle, link);
        if (this._links.has(link)) return handle;
        this._links.add(link);
        link.setListener((m) => this._onMessage(link, m));
        this._fireRoutingChanged();
        return handle;
    }

    /**
     * Attach a fresh in-memory link and hand back its far end alongside the
     * {@link AttachedLink} handle. Creates a {@link TransportPair} internally,
     * {@link attach}es the near side to the hub, and returns the attach handle
     * augmented with `transport` — the far side for a peer (a consumer
     * connection, an in-process participant, …) to drive. Equivalent to
     * `const p = new TransportPair(); const link = hub.attach(p.a);
     * return { ...link, transport: p.b };`. Disposing the returned link also
     * disposes `transport`.
     */
    public attachOut(opts?: AttachLinkOptions): AttachedLink & { readonly transport: IMessageTransport } {
        const pair = new TransportPair();
        const link = this.attach(pair.a, opts);
        const result: AttachedLink & { readonly transport: IMessageTransport } = {
            ...link,
            transport: pair.b,
            dispose: () => {
                link.dispose();
                pair.b.dispose();
            },
        };
        this._topology.registerHandle(result, pair.a);
        return result;
    }

    private _detach(link: IMessageTransport): void {
        if (!this._links.has(link)) {
            return;
        }
        link.setListener(undefined);
        this._links.delete(link);
        this._topology.cleanupLink(link);
        this._table.deleteByValue(link);
        if (this._uplink === link) {
            this._uplink = undefined;
        }
        if (this._loopback === link) {
            this._loopback = undefined;
        }
        for (const [id, p] of [...this._pending]) {
            if (p.origin === link) {
                // The caller is gone. Cancel the callee's now-orphaned work
                // (it streams to nobody) before dropping the entry.
                this._injectCancel(p.target, id, StreamControlReason.clientDisconnected);
                if (!p.inspection && this._transitObservers.size !== 0) {
                    this._emit({
                        ts: Date.now(),
                        nodeId: this.nodeId,
                        in: this._transitEndpoint(p.target, id),
                        disposition: 'dropped',
                        kind: 'response',
                        method: p.method,
                        error: { code: ErrorCode.peerDisconnected, message: 'origin disconnected' },
                    });
                }
                this._deletePending(id);
            } else if (p.target === link) {
                // The target vanished mid-flight; fail the waiting origin
                // instead of leaking the entry and stalling forever.
                this._deletePending(id);
                this._log?.warn(
                    `${this._tag()}target detached mid-request (hubId=${id}); failing origin`,
                );
                if (!p.inspection && this._transitObservers.size !== 0) {
                    this._emit({
                        ts: Date.now(),
                        nodeId: this.nodeId,
                        in: this._transitEndpoint(p.target, id),
                        out: this._transitEndpoint(p.origin, p.originalId),
                        disposition: 'forwarded',
                        kind: 'response',
                        method: p.method,
                        error: { code: ErrorCode.peerDisconnected, message: 'target detached before responding' },
                    });
                }
                this._replyError(
                    p.origin,
                    p.originalId,
                    ErrorCode.peerDisconnected,
                    'target detached before responding',
                );
            }
        }
        this._fireRoutingChanged();
    }

    /** Set (or clear) the default route. Automatically attaches the link. */
    public setUplink(link: IMessageTransport | undefined): void {
        const changed = this._uplink !== link;
        this._uplink = link;
        if (link) {
            this.attach(link);
            this._labelEdge(link, 'uplink');
        }
        if (changed) this._fireRoutingChanged();
    }

    /** Set (or clear) the loopback link serving local root services. */
    public setLoopback(link: IMessageTransport | undefined): void {
        const changed = this._loopback !== link;
        this._loopback = link;
        if (link) {
            this.attach(link);
            this._labelEdge(link, 'loopback');
        }
        if (changed) this._fireRoutingChanged();
    }

    // -- the one privileged seam ------------------------------------

    /**
     * Bind a serviceId `prefix` to `link`. This is the *only* way the
     * forwarding table is written, and therefore the single place any
     * higher layer needs to wrap to enforce who-may-claim-what policy.
     *
     * Claim-once: throws if the prefix is malformed or already owned.
     */
    public claimPrefix(link: IMessageTransport, prefix: ServiceId): void {
        const err = validatePrefix(prefix);
        if (err) throw new Error(`claimPrefix: ${err}`);
        if (this._table.has(prefix)) {
            throw new Error(`claimPrefix: prefix '${prefix}' is already claimed`);
        }
        this.attach(link);
        this._table.set(prefix, link);
        this._labelEdge(link, prefix);
        this._log?.debug(`${this._tag()}claim prefix '${prefix}'`);
        this._fireRoutingChanged();
    }

    public releasePrefix(prefix: ServiceId): boolean {
        const released = this._table.delete(prefix);
        if (released) {
            this._log?.debug(`${this._tag()}release prefix '${prefix}'`);
            this._fireRoutingChanged();
        }
        return released;
    }

    /** Snapshot of currently-claimed prefixes. */
    public claimedPrefixes(): ServiceId[] {
        return this._table.prefixes();
    }

    /**
     * Trust the inspection interfaces mounted for `serviceId` on this attached
     * in-process link. Only exact reserved inspection interface calls are hidden.
     */
    public markInspectionService(attached: AttachedLink, serviceId: ServiceId): void {
        this._topology.markInspectionService(attached, serviceId);
    }

    /** Build a topology snapshot on demand for the addressed observer service. */
    public getTopologyGraph(observerServiceId: string): TopologyGraph {
        return this._topology.getTopologyGraph(observerServiceId);
    }

    /**
     * Fan a **root-form** request out to every distinct downstream participant
     * link (the claimed-prefix owners), skipping the link that owns
     * `excludePrefix` (typically the hub's own services prefix) and the uplink.
     * Each participant is queried **once** even if it owns several prefixes.
     * Failures (unreachable participant, timeout, no root handler) are dropped,
     * so the result holds one entry per link that answered.
     *
     * The request is delivered to each participant's **root** services — on an
     * overlay uplink the splitter routes a root-form method to the participant
     * (`H·root → P`), which is never forwarded and never gated. That is what
     * lets the hub's global directory gather participant self-listings without
     * signing or capabilities.
     */
    public async queryParticipantRoots(
        method: string,
        params: JsonValue,
        excludePrefix?: ServiceId,
    ): Promise<JsonValue[]> {
        return this._participantRoots.query(method, params, excludePrefix);
    }

    /**
     * Keep a root-form streaming request open on every current participant.
     * Routing changes reconcile the participant set; application stream payloads
     * are collapsed into a coarse callback so callers can re-query.
     */
    public watchParticipantRoots(
        method: string,
        params: JsonValue,
        onTick: () => void,
        excludePrefix?: ServiceId,
    ): IDisposable {
        return this._participantRoots.watch(method, params, onTick, excludePrefix);
    }

    /**
     * Send a single request down `link` and resolve with its result — the
     * hub-originated analogue of {@link _routeRequest}. It allocates a hub id,
     * parks a {@link _pending} entry whose `origin` is a tiny in-memory sink
     * that settles this promise on the matching response, and writes the
     * request to `link`. It therefore reuses the full demux / idle-timeout /
     * detach machinery: a response routes back through {@link _demux} into the
     * sink, an idle target fails it via {@link _onIdleTimeout}, and a detaching
     * target fails it via {@link _detach}.
     */
    private _requestOnLink(
        link: IMessageTransport,
        method: string,
        params: JsonValue,
        inspection = false,
        timeoutMs?: number,
    ): Promise<JsonValue | undefined> {
        return new Promise<JsonValue | undefined>((resolve, reject) => {
            const hubId = this._nextId++;
            const key = String(hubId);
            let settled = false;
            let requestTimeout: ReturnType<typeof setTimeout> | undefined;
            const finish = (error: unknown, result?: JsonValue): void => {
                if (settled) return;
                settled = true;
                if (requestTimeout !== undefined) clearTimeout(requestTimeout);
                if (error !== undefined) reject(error);
                else resolve(result);
            };
            const origin: IMessageTransport = {
                send: (m) => {
                    const r = m as JsonRpcResponse;
                    const err = (r as {
                        error?: { code?: number; message?: string; data?: JsonValue; };
                    }).error;
                    if (err) {
                        finish(new RpcError(
                            err.message ?? 'request failed',
                            err.code ?? ErrorCode.internalError,
                            err.data,
                        ));
                    } else {
                        finish(undefined, (r as { result?: JsonValue; }).result);
                    }
                },
                setListener: () => { /* sink: never delivers inbound */ },
                dispose: () => { /* nothing to release */ },
            };
            this._pending.set(key, {
                origin,
                originalId: hubId,
                target: link,
                method,
                startedAtMs: Date.now(),
                inspection,
            });
            this._armIdle(key);
            if (timeoutMs !== undefined && timeoutMs > 0) {
                requestTimeout = setTimeout(() => {
                    if (this._pending.get(key)?.origin !== origin) return;
                    this._injectCancel(link, key, StreamControlReason.clientDisconnected);
                    this._deletePending(key);
                    finish(new Error(`${method} timed out after ${timeoutMs}ms`));
                }, timeoutMs);
            }
            const onSendError = (error: unknown): void => {
                if (this._pending.get(key)?.origin !== origin) return;
                this._deletePending(key);
                finish(error instanceof Error ? error : new Error(String(error)));
            };
            try {
                Promise.resolve(link.send({
                    jsonrpc: '2.0',
                    id: hubId,
                    method,
                    params,
                } as JsonRpcRequest)).catch(onSendError);
            } catch (error) {
                onSendError(error);
            }
        });
    }

    private _watchOnLink(
        link: IMessageTransport,
        method: string,
        params: JsonValue,
        onTick: () => void,
        onSettled: () => void,
        onEstablished: () => void,
    ): IDisposable {
        const hubId = this._nextId++;
        const key = String(hubId);
        let active = true;
        let pingTimer: ReturnType<typeof setInterval> | undefined;
        let establishedTimer: ReturnType<typeof setTimeout> | undefined;
        const stop = (cancel: boolean): void => {
            if (!active) return;
            active = false;
            if (pingTimer !== undefined) clearInterval(pingTimer);
            if (establishedTimer !== undefined) clearTimeout(establishedTimer);
            if (this._pending.get(key)?.origin === origin) {
                if (cancel) this._injectCancel(link, key, StreamControlReason.clientDisconnected);
                this._deletePending(key);
            }
            if (!cancel) onSettled();
        };
        const sendControl = (control: StreamSendParams['control'], dir: StreamDir): void => {
            const message = {
                jsonrpc: '2.0',
                method: STREAM_METHOD,
                params: {
                    requestId: hubId,
                    dir,
                    control,
                },
            } as const;
            try {
                Promise.resolve(link.send(message)).catch(() => stop(false));
            } catch {
                stop(false);
            }
        };
        const origin: IMessageTransport = {
            send: (message) => {
                if (isNotification(message) && message.method === STREAM_METHOD) {
                    const stream = _streamParams(message);
                    if (stream?.dir !== StreamDir.toCaller) return;
                    if (stream.control?.type === StreamControlType.ping) {
                        sendControl({
                            type: StreamControlType.pong,
                            nonce: stream.control.nonce,
                        }, StreamDir.toCallee);
                    }
                    if (stream.payload !== undefined) onTick();
                } else if (isResponse(message)) {
                    stop(false);
                }
            },
            setListener: () => { /* synthetic caller receives through send */ },
            dispose: () => stop(true),
        };
        this._pending.set(key, {
            origin,
            originalId: hubId,
            target: link,
            method,
            startedAtMs: Date.now(),
            inspection: true,
        });
        this._armIdle(key);
        establishedTimer = setTimeout(() => {
            establishedTimer = undefined;
            if (active && this._pending.get(key)?.origin === origin) onEstablished();
        }, 10);
        if (this._idleMs > 0) {
            pingTimer = setInterval(() => {
                if (!active || this._pending.get(key)?.origin !== origin) {
                    stop(false);
                    return;
                }
                this._resetIdle(key);
                sendControl({
                    type: StreamControlType.ping,
                    nonce: randomUUID(),
                }, StreamDir.toCallee);
            }, Math.max(10, Math.floor(this._idleMs / 3)));
        }
        const onSendError = (): void => stop(false);
        try {
            Promise.resolve(link.send({
                jsonrpc: '2.0',
                id: hubId,
                method,
                params,
            } as JsonRpcRequest)).catch(onSendError);
        } catch {
            onSendError();
        }
        return { dispose: () => stop(true) };
    }

    /**
     * The link a still-in-flight forwarded request originally arrived on,
     * keyed by the **hub-rewritten** id the request now carries (i.e. the
     * `id` a target sees on its delivered message). Valid from the moment the
     * hub forwards the request until its response is demultiplexed; returns
     * `undefined` for unknown / already-answered ids.
     *
     * This is the seam a hub-hosted participant uses to learn *which* link a
     * call it is handling came from, so it can bind a prefix claim to that
     * exact link via {@link claimPrefix} without the routing core ever
     * growing a notion of authenticated identity.
     */
    public getSourceTransport(requestId: RequestId): IMessageTransport | undefined {
        return this._pending.get(String(requestId))?.origin;
    }

    // -- routing ----------------------------------------------------

    private _onMessage(from: IMessageTransport, m: JsonRpcMessage): void {
        if (isResponse(m)) {
            this._demux(from, m);
        } else if (isRequest(m)) {
            if (m.method === GET_NODE_ID_METHOD) {
                void from.send({
                    jsonrpc: '2.0',
                    id: m.id,
                    result: { nodeId: this.nodeId, portId: this._topology.portId(from) },
                });
                return;
            }
            this._routeRequest(from, m);
        } else if (isNotification(m)) {
            // `$stream::send` is correlated to an in-flight request by
            // `requestId`, *not* addressed by method name. It must follow that
            // request's established path (like a response demux), never the
            // method-form table — routing it as an interface-form notification
            // would wrongly send it to loopback. See {@link _routeStream}.
            if ((m as { method?: unknown; }).method === STREAM_METHOD) {
                this._routeStream(from, m);
            } else {
                this._routeNotification(from, m);
            }
        }
    }

    private _resolve(method: string, from: IMessageTransport): Resolution {
        const parsed = parseMethodName(method);
        if (!parsed) return { kind: 'malformed' };
        // Root-addressed: loopback only. Structural invariant — never forwarded.
        if (parsed.kind === 'bare' || parsed.kind === 'interface') {
            return { kind: 'loopback', link: this._loopback };
        }
        const match = this._table.longestPrefixMatch(parsed.serviceId);
        if (match) return { kind: 'prefix', link: match.value, prefix: match.prefix };
        // No table hit: fall back to the default route, unless that *is*
        // where the message came from (a loop with no owner downstream).
        if (this._uplink !== undefined && this._uplink === from) {
            return { kind: 'uplink', link: undefined };
        }
        return { kind: 'uplink', link: this._uplink };
    }

    private _isInspectionRequest(
        request: JsonRpcRequest,
        target: IMessageTransport,
    ): boolean {
        if (isInspectionLifecycle(request)) return true;
        const parsed = parseMethodName(request.method);
        return parsed?.kind === 'full'
            && isReservedInspectionInterface(parsed.interfaceId)
            && this._topology.isInspectionService(target, parsed.serviceId);
    }

    private _routeRequest(from: IMessageTransport, req: JsonRpcRequest): void {
        const res = this._resolve(req.method, from);
        const target = res.kind === 'malformed' ? undefined : res.link;
        if (!target) {
            const message = this._noTargetMessage(res, req.method);
            this._log?.warn(
                `${this._tag()}unroutable request '${req.method}' (id=${String(req.id)}): ${message}`,
            );
            if (this._transitObservers.size !== 0) {
                this._emit({
                    ts: Date.now(),
                    nodeId: this.nodeId,
                    in: this._transitEndpoint(from, req.id),
                    disposition: 'unroutable',
                    kind: 'request',
                    method: req.method,
                    params: req.params as JsonValue | undefined,
                });
            }
            this._replyError(from, req.id, this._noTargetCode(res), message);
            return;
        }
        const hubId = this._nextId++;
        const key = String(hubId);
        const inspection = this._isInspectionRequest(req, target);
        this._pending.set(key, {
            origin: from,
            originalId: req.id,
            target,
            method: req.method,
            startedAtMs: Date.now(),
            inspection,
        });
        this._armIdle(key);
        this._log?.trace(
            `${this._tag()}route '${req.method}' (${res.kind}${res.kind === 'prefix' ? ` ${res.prefix}` : ''
            }) id=${String(req.id)}\u2192${hubId}`,
        );
        if (!inspection && this._transitObservers.size !== 0) {
            this._emit({
                ts: Date.now(),
                nodeId: this.nodeId,
                in: this._transitEndpoint(from, req.id),
                out: this._transitEndpoint(target, hubId),
                disposition: 'forwarded',
                kind: 'request',
                method: req.method,
                params: req.params as JsonValue | undefined,
            });
        }
        const forwarded = { ...req, id: hubId };
        if (inspection) markInspectionLifecycle(forwarded);
        const onSendError = (error: unknown): void => {
            const pending = this._pending.get(key);
            if (pending === undefined || pending.target !== target) return;
            this._deletePending(key);
            const message = `target send failed: ${
                error instanceof Error ? error.message : String(error)
            }`;
            this._log?.warn(`${this._tag()}${message} (hubId=${key})`);
            if (!pending.inspection && this._transitObservers.size !== 0) {
                this._emit({
                    ts: Date.now(),
                    nodeId: this.nodeId,
                    in: this._transitEndpoint(pending.target, hubId),
                    out: this._transitEndpoint(pending.origin, pending.originalId),
                    disposition: 'dropped',
                    kind: 'response',
                    method: pending.method,
                    error: { code: ErrorCode.peerDisconnected, message },
                });
            }
            this._replyError(
                pending.origin,
                pending.originalId,
                ErrorCode.peerDisconnected,
                message,
            );
        };
        try {
            Promise.resolve(target.send(forwarded)).catch(onSendError);
        } catch (error) {
            onSendError(error);
        }
    }

    private _routeNotification(from: IMessageTransport, note: JsonRpcMessage): void {
        const method = (note as { method: string; }).method;
        const params = (note as { params?: unknown; }).params as JsonValue | undefined;
        const res = this._resolve(method, from);
        const target = res.kind === 'malformed' ? undefined : res.link;
        // Notifications cannot be answered; silently drop when unroutable.
        if (target) {
            if (this._transitObservers.size !== 0) {
                this._emit({
                    ts: Date.now(),
                    nodeId: this.nodeId,
                    in: this._transitEndpoint(from),
                    out: this._transitEndpoint(target),
                    disposition: 'forwarded',
                    kind: 'notification',
                    method,
                    params,
                });
            }
            void target.send(note);
        } else {
            if (this._transitObservers.size !== 0) {
                this._emit({
                    ts: Date.now(),
                    nodeId: this.nodeId,
                    in: this._transitEndpoint(from),
                    disposition: res.kind === 'malformed' ? 'unroutable' : 'dropped',
                    kind: 'notification',
                    method,
                    params,
                });
            }
            this._log?.trace(`${this._tag()}drop unroutable notification '${method}'`);
        }
    }

    private _demux(from: IMessageTransport, res: JsonRpcResponse): void {
        if (res.id === null) return;
        const key = String(res.id);
        const pending = this._pending.get(key);
        if (!pending) return; // unknown / late response — drop
        // Only the link the request was forwarded to may answer it. This
        // blocks a malicious downstream from forging a reply (with a guessed
        // sequential id) to a request routed to a different link.
        if (from !== pending.target) return;
        this._deletePending(key);
        if (!pending.inspection && this._transitObservers.size !== 0) {
            this._emit({
                ts: Date.now(),
                nodeId: this.nodeId,
                in: this._transitEndpoint(pending.target, res.id),
                out: this._transitEndpoint(pending.origin, pending.originalId),
                disposition: 'forwarded',
                kind: 'response',
                method: pending.method,
                result: (res as { result?: JsonValue; }).result,
                error: (res as { error?: TransitError; }).error,
            });
        }
        void pending.origin.send({ ...res, id: pending.originalId });
    }

    /**
     * Route a `$stream::send` notification. Unlike an ordinary notification, a
     * stream message is **correlated to an in-flight request by `requestId`**,
     * not addressed by method name — so it follows the same path the request
     * established (recorded in {@link _pending}), exactly like a
     * {@link _demux | response}, and the hub rewrites `requestId` across the
     * forwarding boundary the same way it rewrites a response `id`.
     *
     * The message's explicit `dir` picks the traversal — no inference from the
     * arriving link:
     *
     * - **`toCaller`** (callee → caller progress): routed like a response. The
     *   streamer used the hub-rewritten id it *received*, so `requestId` is a
     *   pending hub id; only the link the request was forwarded to may stream
     *   on it. Restore the origin's original id and forward to the origin.
     * - **`toCallee`** (caller → callee input / cancel / ping): the reverse
     *   traversal of the same entry. The streamer used the original id it
     *   *sent*; rewrite `requestId` to the hub id the target was handed and
     *   forward to the target. Only the origin may stream this direction.
     *
     * Every routed stream message resets the request's idle timer (a keepalive
     * ping is exactly a `toCallee` control with no payload). A `$stream::send`
     * matching no in-flight request is dropped (late / unknown correlation).
     */
    private _routeStream(from: IMessageTransport, note: JsonRpcMessage): void {
        const p = _streamParams(note);
        if (!p || p.requestId === undefined) {
            this._log?.trace(`${this._tag()}drop malformed '${STREAM_METHOD}' (no requestId)`);
            return;
        }
        if (p.dir === StreamDir.toCaller) {
            // Like a response: keyed by the hub-rewritten id; only the link the
            // request was forwarded to may stream back toward the caller.
            const key = String(p.requestId);
            const pending = this._pending.get(key);
            if (!pending || from !== pending.target) {
                this._log?.trace(
                    `${this._tag()}drop unroutable toCaller '${STREAM_METHOD}' requestId=${String(p.requestId)}`,
                );
                return;
            }
            this._resetIdle(key);
            void pending.origin.send(_withRequestId(note, pending.originalId));
            if (!pending.inspection && this._transitObservers.size !== 0) {
                this._emitStream(
                    note,
                    this._transitEndpoint(pending.target, p.requestId),
                    this._transitEndpoint(pending.origin, pending.originalId),
                );
            }
            return;
        }
        // toCallee: reverse traversal. The origin streams with the id it sent;
        // rewrite `requestId` to the hub-local id the target was handed.
        for (const [hubId, pending] of this._pending) {
            if (pending.origin === from && String(pending.originalId) === String(p.requestId)) {
                this._resetIdle(hubId);
                void pending.target.send(_withRequestId(note, Number(hubId)));
                if (!pending.inspection && this._transitObservers.size !== 0) {
                    this._emitStream(
                        note,
                        this._transitEndpoint(pending.origin, p.requestId),
                        this._transitEndpoint(pending.target, Number(hubId)),
                    );
                }
                return;
            }
        }
        this._log?.trace(
            `${this._tag()}drop unroutable toCallee '${STREAM_METHOD}' requestId=${String(p.requestId)}`,
        );
    }

    // -- pending lifecycle ------------------------------------------

    /** Delete a pending entry and clear its idle timer. */
    private _deletePending(key: string): void {
        const p = this._pending.get(key);
        if (!p) return;
        if (p.timer !== undefined) clearTimeout(p.timer);
        this._pending.delete(key);
    }

    /** Arm (or re-arm) the idle timer for a pending entry. No-op when disabled. */
    private _armIdle(key: string): void {
        if (this._idleMs <= 0) return;
        const t = setTimeout(() => this._onIdleTimeout(key), this._idleMs);
        (t as { unref?: () => void; }).unref?.();
        const p = this._pending.get(key);
        if (p) p.timer = t;
        else clearTimeout(t);
    }

    /** Reset the idle timer on stream activity. */
    private _resetIdle(key: string): void {
        const p = this._pending.get(key);
        if (!p) return;
        if (p.timer !== undefined) clearTimeout(p.timer);
        this._armIdle(key);
    }

    /**
     * A request went idle past {@link _idleMs}. Cancel the (presumably hung)
     * callee, fail the caller with a `requestTimeout`, and drop the entry —
     * the bound that keeps `_pending` from growing without limit.
     */
    private _onIdleTimeout(key: string): void {
        const p = this._pending.get(key);
        if (!p) return;
        this._log?.warn(`${this._tag()}request idle-timed-out (hubId=${key}); cancelling + failing origin`);
        this._injectCancel(p.target, key, StreamControlReason.idleTimeout);
        this._deletePending(key);
        if (!p.inspection && this._transitObservers.size !== 0) {
            this._emit({
                ts: Date.now(),
                nodeId: this.nodeId,
                in: this._transitEndpoint(p.target, key),
                out: this._transitEndpoint(p.origin, p.originalId),
                disposition: 'forwarded',
                kind: 'response',
                method: p.method,
                error: { code: ErrorCode.requestTimeout, message: 'request idle-timed-out' },
            });
        }
        this._replyError(
            p.origin,
            p.originalId,
            ErrorCode.requestTimeout,
            'request idle-timed-out',
        );
    }

    /**
     * Author a `toCallee` cancel toward `target` for the request the target
     * knows as `hubId`. Used on caller-disconnect and idle-timeout — the hub
     * itself originates the message, which is why `dir` is explicit on the
     * wire (there is no inbound link to infer it from).
     */
    private _injectCancel(target: IMessageTransport, hubId: string, reason: string): void {
        const params: StreamSendParams = {
            requestId: Number(hubId),
            dir: StreamDir.toCallee,
            control: { type: StreamControlType.cancel, reason },
        };
        try {
            Promise.resolve(
                target.send({ jsonrpc: '2.0', method: STREAM_METHOD, params } as unknown as JsonRpcMessage),
            ).catch(() => undefined);
        } catch {
            // Best-effort cancellation during teardown/timeout.
        }
    }

    // -- error replies ----------------------------------------------

    private _noTargetCode(res: Resolution): number {
        return res.kind === 'malformed' ? ErrorCode.invalidRequest : ErrorCode.methodNotFound;
    }

    private _noTargetMessage(res: Resolution, method: string): string {
        switch (res.kind) {
            case 'malformed':
                return `malformed method name: ${method}`;
            case 'loopback':
                return `no local root services to handle: ${method}`;
            case 'uplink':
                return `no route for: ${method}`;
            default:
                return `unroutable: ${method}`;
        }
    }

    private _replyError(to: IMessageTransport, id: RequestId, code: number, message: string): void {
        const error: JsonRpcResponse = {
            jsonrpc: '2.0',
            id,
            error: this._options.debugName !== undefined ?
                { code, message, data: { hub: this._options.debugName } } :
                { code, message },
        };
        void to.send(error);
    }
}

/** Read the params off a {@link STREAM_METHOD} notification. */
function _streamParams(m: JsonRpcMessage): StreamSendParams | undefined {
    const params = (m as { params?: unknown; }).params;
    if (params === null || typeof params !== 'object') return undefined;
    return params as StreamSendParams;
}

/** Clone a {@link STREAM_METHOD} notification with `requestId` replaced. */
function _withRequestId(m: JsonRpcMessage, requestId: RequestId): JsonRpcMessage {
    const params = { ...(m as { params?: object; }).params, requestId };
    return { ...m, params } as JsonRpcMessage;
}
