// @generated by linkrpc::schema::codegen from interface `cdp.debugger`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"cdp.debugger\",\"hash\":\"249318446cfe090d\",\"methods\":{\"inspect\":{\"params\":{\"$ref\":\"#/components/schemas/Runtime.RemoteObject\"},\"result\":{\"$ref\":\"#/components/schemas/Runtime.RemoteObject\"}}},\"components\":{\"schemas\":{\"Runtime.RemoteObject\":{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"additionalProperties\":false},\"Shared.Node\":{\"type\":\"object\",\"properties\":{\"next\":{\"$ref\":\"#/components/schemas/Shared.Node\"}},\"additionalProperties\":false}}}}",
    client = "CdpDebuggerClient",
    server = "CdpDebuggerServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
pub trait CdpDebuggerService {
    #[name("inspect")]
    async fn inspect(value: String) -> Result<super::types::RuntimeRemoteObject, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, value,);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "inspect"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;

pub const SERVICE_1: linkrpc::binding::InterfaceBinding<CdpDebuggerClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Service("debug"));

pub const BARE_1: linkrpc::binding::InterfaceBinding<CdpDebuggerClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Bare("Debugger."));
