// @generated by linkrpc::schema::codegen from an endpoint contract.
// Do not edit by hand; regenerate from the contract instead.
#![cfg_attr(rustfmt, rustfmt::skip)]
pub mod types;
pub mod cdp_debugger;
pub mod cdp_runtime;
