// @generated by hubrpc::schema::codegen from interface `com.example.graph`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

/// An open object with a known field plus arbitrary extras.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Bag {
    pub id: String,
    /// Additional properties not captured by named fields.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

impl Bag {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(id: String) -> Self {
        Self {
            id,
            extra: Default::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Color {
    #[serde(rename = "red")]
    Red,
    #[serde(rename = "green")]
    Green,
    #[serde(rename = "blue")]
    Blue,
    #[serde(rename = "self")]
    Self_,
}

/// A recursive JSON value, recursing only through arrays and maps.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum JsonNode {
    Variant0(String),
    Variant1(f64),
    Variant2(bool),
    Variant3(Vec<JsonNode>),
    Variant4(std::collections::HashMap<String, JsonNode>),
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Metadata {
    /// Additional properties not captured by named fields.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, String>,
}

impl Metadata {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {
            extra: Default::default(),
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Ping {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pong: Option<Box<Pong>>,
}

impl Ping {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {
            pong: None,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

impl Point {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(x: f64, y: f64) -> Self {
        Self {
            x,
            y,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Pong {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ping: Option<Box<Ping>>,
}

impl Pong {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {
            ping: None,
        }
    }
}

/// A tagged union of shapes.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
#[serde(tag = "kind")]
pub enum Shape {
    #[serde(rename = "circle")]
    Circle {
        radius: f64,
    },
    #[serde(rename = "rectangle")]
    Rectangle {
        width: f64,
        height: f64,
    },
    #[serde(rename = "point")]
    Point,
}

pub type Tags = Vec<String>;

/// A recursive tree node.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct TreeNode {
    pub value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub point: Option<Point>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<TreeNode>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<TreeNode>>,
}

impl TreeNode {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(value: String) -> Self {
        Self {
            value,
            point: None,
            parent: None,
            children: None,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ConfigureParams {
    pub id: String,
    /// Optional display label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ConfigureParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(id: String) -> Self {
        Self {
            id,
            label: None,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct GetTreeParams {
    pub id: String,
}

impl GetTreeParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(id: String) -> Self {
        Self {
            id,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct NotifyChangedParams {
    pub node: TreeNode,
}

impl NotifyChangedParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(node: TreeNode) -> Self {
        Self {
            node,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct PaintParams {
    pub shape: Shape,
    pub color: Color,
}

impl PaintParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(shape: Shape, color: Color) -> Self {
        Self {
            shape,
            color,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ResetParams {}

impl ResetParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {}
    }
}

/// A demo interface exercising the full codegen surface.
#[derive(Clone)]
pub struct ComExampleGraphClient<C> {
    caller: C,
    prefix: String,
}

impl<C: hubrpc::prelude::RpcCall> ComExampleGraphClient<C> {
    /// The interface id (the `id` half of `id@hash`).
    pub const INTERFACE_ID: &'static str = "com.example.graph";

    /// Address members with the interface-qualified name `id::member`.
    pub fn new(caller: C) -> Self {
        Self { caller, prefix: format!("{}::", Self::INTERFACE_ID) }
    }

    /// Address members by bare method name (root-addressed, e.g. a CDP channel).
    pub fn root(caller: C) -> Self {
        Self { caller, prefix: String::new() }
    }

    /// Address members under a specific service id: `service::id::member`.
    pub fn with_service(caller: C, service_id: &str) -> Self {
        Self { caller, prefix: format!("{}::{}::", service_id, Self::INTERFACE_ID) }
    }

    /// Address members with an explicit wire-name prefix (e.g. `"Page."`).
    pub fn with_prefix(caller: C, prefix: impl Into<String>) -> Self {
        Self { caller, prefix: prefix.into() }
    }

    fn method_name(&self, member: &str) -> String {
        format!("{}{}", self.prefix, member)
    }

    /// A method whose params mix required and optional fields.
    pub async fn configure(&self, params: ConfigureParams) -> Result<bool, hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __v = self.caller.call(&self.method_name("configure"), __p).await?;
        serde_json::from_value(__v).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })
    }

    /// Fetch the tree rooted at an id.
    pub async fn get_tree(&self, params: GetTreeParams) -> Result<TreeNode, hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __v = self.caller.call(&self.method_name("get_tree"), __p).await?;
        serde_json::from_value(__v).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })
    }

    pub async fn notify_changed(&self, params: NotifyChangedParams) -> Result<(), hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        self.caller.notify(&self.method_name("notify_changed"), __p).await
    }

    pub async fn paint(&self, params: PaintParams) -> Result<bool, hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __v = self.caller.call(&self.method_name("paint"), __p).await?;
        serde_json::from_value(__v).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })
    }

    pub async fn raw_echo(&self, params: serde_json::Value) -> Result<serde_json::Value, hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __v = self.caller.call(&self.method_name("raw_echo"), __p).await?;
        serde_json::from_value(__v).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })
    }

    /// A method with an empty (all-defaults) params object.
    pub async fn reset(&self, params: ResetParams) -> Result<(), hubrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            hubrpc::prelude::JsonRpcError::new(hubrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        self.caller.notify(&self.method_name("reset"), __p).await
    }

    /// Server-emitted event fired whenever the tree changes.
    /// Server notification (server→client, `x-hubrpc-codegen.kind = "serverNotification"`).
    /// No client send method is generated; decode inbound payloads as `TreeNode`.
    pub fn tree_changed_event_name(&self) -> String {
        self.method_name("tree_changed")
    }
}
