[workspace]
resolver = "2"
members = [
    "crates/linkrpc",
    "crates/linkrpc-macros",
    "crates/linkrpc-tokio",
    "crates/linkrpc-examples",
]
exclude = ["crates/linkrpc/tests/compile_fail"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/hediet/linkrpc"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
thiserror = "1"
async-trait = "0.1"
futures = "0.3"
sha2 = "0.10"
schemars = "0.8"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
url = "2"
percent-encoding = "2"
