// @generated by linkrpc::schema::codegen from interface `shared components`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct RuntimeRemoteObject {
    pub value: String,
}

impl RuntimeRemoteObject {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(value: String) -> Self {
        Self {
            value,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct SharedNode {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Box<SharedNode>>,
}

impl SharedNode {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {
            next: None,
        }
    }
}
