// @generated by linkrpc::schema::codegen from interface `inline`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct EmptyPayload {}

impl EmptyPayload {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {}
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct EmptyParams {}

impl EmptyParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {}
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct SendParams {
    #[serde(rename = "camelCase")]
    pub camel_case: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    pub r#type: String,
    #[serde(rename = "wire-key")]
    pub wire_key: i64,
}

impl SendParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(camel_case: String, r#type: String, wire_key: i64) -> Self {
        Self {
            camel_case,
            optional: None,
            payload: None,
            r#type,
            wire_key,
        }
    }
}

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"inline\",\"hash\":\"\",\"methods\":{\"disable\":{\"params\":{\"$ref\":\"#/components/schemas/EmptyPayload\"},\"result\":true},\"empty\":{\"params\":{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}},\"send\":{\"params\":{\"type\":\"object\",\"properties\":{\"camelCase\":{\"type\":\"string\"},\"optional\":{\"type\":\"boolean\"},\"payload\":true,\"type\":{\"type\":\"string\"},\"wire-key\":{\"type\":\"integer\"}},\"required\":[\"camelCase\",\"type\",\"wire-key\"],\"additionalProperties\":false},\"result\":true}},\"components\":{\"schemas\":{\"EmptyPayload\":{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}}}}",
    omit_optional_params = true,
    client = "InlineClient",
    server = "InlineServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
pub trait InlineService {
    #[name("disable")]
    async fn disable() -> Result<serde_json::Value, linkrpc::prelude::RpcCallError>;
    #[name("empty")]
    #[notification]
    async fn empty() -> Result<(), linkrpc::prelude::RpcCallError>;
    #[name("send")]
    async fn send(
        #[serde(rename = "camelCase")] camel_case: String,
        optional: Option<bool>,
        payload: Option<serde_json::Value>,
        r#type: String,
        #[serde(rename = "wire-key")] wire_key: i64,
    ) -> Result<serde_json::Value, linkrpc::prelude::RpcCallError>;
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
