// @generated by linkrpc::schema::codegen from interface `cdp.runtime`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct RuntimeEvaluateParams {
    pub expression: String,
}

impl RuntimeEvaluateParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(expression: String) -> Self {
        Self {
            expression,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct RuntimeEvaluateResult {
    pub object: super::shared::RuntimeRemoteObject,
}

impl RuntimeEvaluateResult {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(object: super::shared::RuntimeRemoteObject) -> Self {
        Self {
            object,
        }
    }
}

#[derive(Clone, Debug, linkrpc::prelude::ApplicationError)]
#[rpc_error(schema = __linkrpc_interface::schema, method = "fallible", runtime = "linkrpc", display)]
pub enum RuntimeFallibleError {
    #[rpc_error(code = 41, message = "failed")]
    Code41,
}

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"cdp.runtime\",\"hash\":\"428079033d035d03\",\"methods\":{\"changed\":{\"params\":{\"$ref\":\"#/components/schemas/Runtime.RemoteObject\"},\"x-linkrpc-codegen\":{\"kind\":\"serverNotification\"}},\"evaluate\":{\"params\":{\"type\":\"object\",\"properties\":{\"expression\":{\"type\":\"string\"}},\"required\":[\"expression\"],\"additionalProperties\":false},\"result\":{\"type\":\"object\",\"properties\":{\"object\":{\"$ref\":\"#/components/schemas/Runtime.RemoteObject\"}},\"required\":[\"object\"],\"additionalProperties\":false}},\"fallible\":{\"params\":true,\"result\":true,\"errors\":[{\"code\":41,\"message\":\"failed\"}]},\"unsupported\":{\"params\":true,\"result\":true}},\"components\":{\"schemas\":{\"Runtime.RemoteObject\":{\"type\":\"object\",\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"additionalProperties\":false},\"Shared.Node\":{\"type\":\"object\",\"properties\":{\"next\":{\"$ref\":\"#/components/schemas/Shared.Node\"}},\"additionalProperties\":false}}}}",
    omit_optional_params = true,
    client = "RuntimeClient",
    server = "RuntimeServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
pub trait RuntimeService {
    #[name("changed")]
    #[server_notification]
    async fn changed(value: String) -> Result<(), linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, value,);
        Ok(())
    }
    #[name("evaluate")]
    async fn evaluate(expression: String) -> Result<RuntimeEvaluateResult, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, expression,);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "evaluate"))
    }
    #[name("fallible")]
    async fn fallible(#[params] params: serde_json::Value) -> Result<serde_json::Value, linkrpc::prelude::CallError<RuntimeFallibleError>> {
        let _ = (ctx, params,);
        Err(linkrpc::prelude::CallError::Generic(linkrpc::prelude::RpcCallError::Local(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "fallible"))))
    }
    #[name("unsupported")]
    async fn unsupported(#[params] params: serde_json::Value) -> Result<serde_json::Value, linkrpc::prelude::JsonRpcError> {
        let _ = (ctx, params,);
        Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, "unsupported"))
    }
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;

pub const TARGET: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Bare("Runtime."));

pub const ROOT: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Root);

pub const SERVICE: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Service("debug"));

pub const EMPTY_SERVICE: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Service(""));

pub const DEFAULT: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Default);

pub const BARE: linkrpc::binding::InterfaceBinding<RuntimeClient> = linkrpc::binding::InterfaceBinding::new(linkrpc::binding::BindingAddress::Bare(""));
