// @generated by linkrpc::schema::codegen from interface `com.example.generated-streaming`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Command {
    pub amount: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Box<Command>>,
}

impl Command {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(amount: u32) -> Self {
        Self {
            amount,
            next: None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EventKind {
    #[serde(rename = "progress")]
    Progress,
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Event {
    pub kind: EventKind,
    pub total: u32,
}

impl Event {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(kind: EventKind, total: u32) -> Self {
        Self {
            kind,
            total,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ExchangeParams {
    pub initial: u32,
}

impl ExchangeParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(initial: u32) -> Self {
        Self {
            initial,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ServerSilentParams {}

impl ServerSilentParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {}
    }
}

#[derive(Clone)]
pub struct ComExampleGeneratedStreamingClient<C> {
    caller: C,
    prefix: String,
}

impl<C: linkrpc::prelude::RpcCall> ComExampleGeneratedStreamingClient<C> {
    /// The interface id (the `id` half of `id@hash`).
    pub const INTERFACE_ID: &'static str = "com.example.generated-streaming";

    /// Address members with the interface-qualified name `id::member`.
    pub fn new(caller: C) -> Self {
        Self { caller, prefix: format!("{}::", Self::INTERFACE_ID) }
    }

    /// Address members by bare method name (root-addressed, e.g. a CDP channel).
    pub fn root(caller: C) -> Self {
        Self { caller, prefix: String::new() }
    }

    /// Address members under a specific service id: `service::id::member`.
    pub fn with_service(caller: C, service_id: &str) -> Self {
        Self { caller, prefix: format!("{}::{}::", service_id, Self::INTERFACE_ID) }
    }

    /// Address members with an explicit wire-name prefix (e.g. `"Page."`).
    pub fn with_prefix(caller: C, prefix: impl Into<String>) -> Self {
        Self { caller, prefix: prefix.into() }
    }

    fn method_name(&self, member: &str) -> String {
        format!("{}{}", self.prefix, member)
    }

    pub async fn exchange(&self, params: ExchangeParams) -> Result<linkrpc::prelude::StreamingCall<u32, Command, Event>, linkrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __call = self.caller.call_stream(&self.method_name("exchange"), __p).await?;
        Ok(__call.typed::<u32, Command, Event>(Some(serde_json::from_str("{\"allOf\":[{\"$ref\":\"#/components/schemas/Command\"}],\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}").expect("generated stream schema is valid")), Some(serde_json::from_str("{\"allOf\":[{\"$ref\":\"#/components/schemas/Event\"}],\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}").expect("generated stream schema is valid"))))
    }

    pub async fn server_silent(&self, params: ServerSilentParams) -> Result<linkrpc::prelude::StreamingCall<(), linkrpc::prelude::NoStream, linkrpc::prelude::NoStream>, linkrpc::prelude::JsonRpcError> {
        let __p = serde_json::to_value(&params).map_err(|e| {
            linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
        })?;
        let __call = self.caller.call_stream(&self.method_name("server_silent"), __p).await?;
        Ok(__call.typed::<(), linkrpc::prelude::NoStream, linkrpc::prelude::NoStream>(None, Some(serde_json::from_str("{\"allOf\":[false],\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}").expect("generated stream schema is valid"))))
    }
}

/// Build the exact interface schema supplied to the generator.
pub fn interface() -> linkrpc::prelude::InterfaceDefinition {
    let schema: linkrpc::prelude::LinkRpcInterfaceSchema = serde_json::from_str("{\"id\":\"com.example.generated-streaming\",\"hash\":\"\",\"methods\":{\"exchange\":{\"params\":{\"type\":\"object\",\"properties\":{\"initial\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"initial\"],\"additionalProperties\":false},\"result\":{\"type\":\"integer\",\"format\":\"uint32\"},\"clientStream\":{\"$ref\":\"#/components/schemas/Command\"},\"serverStream\":{\"$ref\":\"#/components/schemas/Event\"}},\"server_silent\":{\"params\":{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false},\"result\":{\"type\":\"null\"},\"serverStream\":false}},\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}").expect("generated interface schema is valid");
    linkrpc::prelude::InterfaceDefinition::from_schema(schema)
}

#[linkrpc::prelude::async_trait]
pub trait ComExampleGeneratedStreamingService: Send + Sync {
    async fn exchange(&self, ctx: &linkrpc::prelude::CallCtx, params: ExchangeParams, stream_receiver: linkrpc::prelude::StreamReceiver<Command>, stream_sender: linkrpc::prelude::StreamSender<Event>) -> Result<u32, linkrpc::prelude::JsonRpcError>;
    async fn server_silent(&self, ctx: &linkrpc::prelude::CallCtx, params: ServerSilentParams, stream_sender: linkrpc::prelude::StreamSender<linkrpc::prelude::NoStream>) -> Result<(), linkrpc::prelude::JsonRpcError>;
}

/// Server adapter wrapping a typed provider implementation.
pub struct ComExampleGeneratedStreamingServer<T: ComExampleGeneratedStreamingService + 'static>(pub std::sync::Arc<T>);

impl<T: ComExampleGeneratedStreamingService + 'static> ComExampleGeneratedStreamingServer<T> {
    pub fn new(inner: std::sync::Arc<T>) -> Self {
        Self(inner)
    }

    /// Build the exact interface schema supplied to the generator.
    pub fn interface() -> linkrpc::prelude::InterfaceDefinition {
        interface()
    }

    /// Dispatch an inbound notification without swallowing decode or handler errors.
    ///
    /// Returns `true` when `method` is declared by the schema, including when its
    /// generated service method uses the default no-op implementation, and `false`
    /// for an unknown method. This reports schema recognition, not whether an
    /// application override consumed the notification; raw observers should run
    /// independently when they must retain every inbound notification.
    pub async fn dispatch_notification(&self, method: &str, params: serde_json::Value) -> Result<bool, linkrpc::prelude::JsonRpcError> {
        self.dispatch_notification_with_ctx(method, params, linkrpc::prelude::CallCtx::default()).await
    }

    async fn dispatch_notification_with_ctx(
        &self,
        method: &str,
        params: serde_json::Value,
        ctx: linkrpc::prelude::CallCtx,
    ) -> Result<bool, linkrpc::prelude::JsonRpcError> {
        match method {
            _ => Ok(false),
        }
    }
}

impl<T: ComExampleGeneratedStreamingService + 'static> linkrpc::prelude::ServiceExport for ComExampleGeneratedStreamingServer<T> {
    fn interface() -> linkrpc::prelude::InterfaceDefinition {
        Self::interface()
    }
}

#[linkrpc::prelude::async_trait]
impl<T: ComExampleGeneratedStreamingService + 'static> linkrpc::prelude::InterfaceHandler for ComExampleGeneratedStreamingServer<T> {
    async fn handle_request(
        &self,
        member: &str,
        params: linkrpc::prelude::JsonValue,
        ctx: linkrpc::prelude::CallCtx,
    ) -> Result<linkrpc::prelude::JsonValue, linkrpc::prelude::JsonRpcError> {
        match member {
            "exchange" => {
                let __p: ExchangeParams = serde_json::from_value(params).map_err(|e| {
                    linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INVALID_PARAMS, e.to_string())
                })?;
                let __stream_receiver = ctx.stream_receiver(serde_json::from_str("{\"allOf\":[{\"$ref\":\"#/components/schemas/Command\"}],\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}").expect("generated stream schema is valid"))?;
                let __stream_sender = ctx.stream_sender()?;
                let __r = self.0.exchange(&ctx, __p, __stream_receiver, __stream_sender).await?;
                serde_json::to_value(__r).map_err(|e| {
                    linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
                })
            }
            "server_silent" => {
                let __p: ServerSilentParams = serde_json::from_value(params).map_err(|e| {
                    linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INVALID_PARAMS, e.to_string())
                })?;
                let __stream_sender = ctx.stream_sender()?;
                let __r = self.0.server_silent(&ctx, __p, __stream_sender).await?;
                serde_json::to_value(__r).map_err(|e| {
                    linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::INTERNAL_ERROR, e.to_string())
                })
            }
            _ => Err(linkrpc::prelude::JsonRpcError::new(linkrpc::prelude::error_codes::METHOD_NOT_FOUND, member)),
        }
    }

    async fn handle_notification(
        &self,
        member: &str,
        params: linkrpc::prelude::JsonValue,
        ctx: linkrpc::prelude::CallCtx,
    ) {
        if let Err(__e) = self.dispatch_notification_with_ctx(member, params, ctx).await {
            if __e.code == linkrpc::prelude::error_codes::INVALID_PARAMS {
                eprintln!("linkrpc notification `{}` has invalid params: {}", member, __e.message);
            } else {
                eprintln!("linkrpc notification `{}` handler error {}: {}", member, __e.code, __e.message);
            }
        }
    }
}
