// @generated by linkrpc::schema::codegen from interface `com.example.generated-streaming`.
// Do not edit by hand; regenerate from the interface schema instead.
#![allow(dead_code, clippy::all, non_camel_case_types)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Command {
    pub amount: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<Box<Command>>,
}

impl Command {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(amount: u32) -> Self {
        Self {
            amount,
            next: None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum EventKind {
    #[serde(rename = "progress")]
    Progress,
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct Event {
    pub kind: EventKind,
    pub total: u32,
}

impl Event {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(kind: EventKind, total: u32) -> Self {
        Self {
            kind,
            total,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ExchangeParams {
    pub initial: u32,
}

impl ExchangeParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new(initial: u32) -> Self {
        Self {
            initial,
        }
    }
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ServerSilentParams {}

impl ServerSilentParams {
    /// Construct with all required fields; optional fields default to `None`
    /// and any open-object extra map defaults to `Default::default()`.
    pub fn new() -> Self {
        Self {}
    }
}

#[linkrpc::prelude::link_rpc_interface(
    schema_json = "{\"id\":\"com.example.generated-streaming\",\"hash\":\"\",\"methods\":{\"exchange\":{\"params\":{\"type\":\"object\",\"properties\":{\"initial\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"initial\"],\"additionalProperties\":false},\"result\":{\"type\":\"integer\",\"format\":\"uint32\"},\"clientStream\":{\"$ref\":\"#/components/schemas/Command\"},\"serverStream\":{\"$ref\":\"#/components/schemas/Event\"}},\"server_silent\":{\"params\":{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false},\"result\":{\"type\":\"null\"},\"serverStream\":false}},\"components\":{\"schemas\":{\"Command\":{\"type\":\"object\",\"properties\":{\"amount\":{\"type\":\"integer\",\"format\":\"uint32\"},\"next\":{\"$ref\":\"#/components/schemas/Command\"}},\"required\":[\"amount\"],\"additionalProperties\":false},\"Event\":{\"type\":\"object\",\"properties\":{\"kind\":{\"type\":\"string\",\"enum\":[\"progress\"]},\"total\":{\"type\":\"integer\",\"format\":\"uint32\"}},\"required\":[\"kind\",\"total\"],\"additionalProperties\":false}}}}",
    client = "ComExampleGeneratedStreamingClient",
    server = "ComExampleGeneratedStreamingServer",
    module = "__linkrpc_interface",
    generate_server = true,
    runtime = "linkrpc",
)]
pub trait ComExampleGeneratedStreamingService {
    #[name("exchange")]
    #[input_stream(Command)]
    #[output_stream(Event)]
    async fn exchange(initial: u32) -> Result<u32, linkrpc::prelude::JsonRpcError>;
    #[name("server_silent")]
    #[output_stream(linkrpc::prelude::NoStream)]
    async fn server_silent() -> Result<(), linkrpc::prelude::JsonRpcError>;
}

#[allow(unused_imports)]
pub use __linkrpc_interface::interface;
