use std::collections::{BTreeMap, BTreeSet};

use crate::schema::{Components, ContractError, InterfaceRef, LinkRpcContract};

use super::{
    generate_rust_components, generate_rust_interface, ident, GenerateRustBinding,
    GenerateRustOptions, InterfaceAddress,
};

/// Deterministic sibling modules. Write every entry in `files` into one directory.
#[derive(Debug, Clone)]
pub struct GeneratedRustContract {
    /// Includes `mod.rs`, `types.rs`, and one file per interface identity.
    pub files: BTreeMap<String, String>,
    /// Exact interface identity to generated module name.
    pub modules: BTreeMap<InterfaceRef, String>,
    pub unsupported: Vec<String>,
}

/// Generate an endpoint contract using the same interface and component generators.
///
/// Component names shared between interfaces must describe identical schemas.
/// `ROOT`, `SERVICE_<n>`, `DEFAULT`, and `BARE_<n>` constants are emitted in the
/// corresponding interface modules. Numeric suffixes refer to contract array
/// positions. A schema alone produces no bindings.
pub fn generate_rust_contract(
    contract: &LinkRpcContract,
    options: &GenerateRustOptions,
) -> Result<GeneratedRustContract, ContractError> {
    contract.validate()?;
    let mut components = BTreeMap::new();
    for schema in &contract.interface_schemas {
        if let Some(schemas) = schema.components.as_ref().and_then(|c| c.schemas.as_ref()) {
            for (name, value) in schemas {
                if components.get(name).is_some_and(|old| old != value) {
                    return Err(ContractError(format!(
                        "conflicting shared component `{name}`"
                    )));
                }
                components.insert(name.clone(), value.clone());
            }
        }
    }
    let shared = generate_rust_components(
        &Components {
            schemas: Some(components),
        },
        options,
    );
    let mut files = BTreeMap::from([("types.rs".to_string(), shared.code)]);
    let mut unsupported = shared.unsupported;
    let mut modules = BTreeMap::new();
    let mut used_modules = BTreeSet::from(["mod".to_string(), "types".to_string()]);
    let mut module_source = String::from(
        "// @generated by linkrpc::schema::codegen from an endpoint contract.\n\
         // Do not edit by hand; regenerate from the contract instead.\n\
         #![cfg_attr(rustfmt, rustfmt::skip)]\n\
         pub mod types;\n",
    );
    let mut schemas: Vec<_> = contract.interface_schemas.iter().collect();
    schemas.sort_by_key(|schema| InterfaceRef::from(*schema));
    for schema in schemas {
        let reference = InterfaceRef::from(schema);
        let name = ident::to_snake_case(&schema.id);
        let base = match ident::strip_raw(&name) {
            "_" => "interface".to_string(),
            name => name.to_string(),
        };
        let mut file_stem = base.clone();
        let mut suffix = 2;
        while !used_modules.insert(file_stem.clone()) {
            file_stem = format!("{}_{suffix}", base.trim_end_matches('_'));
            suffix += 1;
        }
        let module = ident::escape_ident(file_stem.clone());
        let mut interface_options = options.clone();
        interface_options
            .external_components
            .extend(shared.names.iter().map(|(name, ty)| {
                (
                    name.clone(),
                    options
                        .external_components
                        .get(name)
                        .cloned()
                        .unwrap_or_else(|| format!("super::types::{ty}")),
                )
            }));
        for (index, service) in contract
            .services
            .as_deref()
            .unwrap_or_default()
            .iter()
            .enumerate()
        {
            if service.interfaces.contains(&reference) {
                interface_options.bindings.push(GenerateRustBinding {
                    name: if service.service_id.is_empty() {
                        "ROOT".to_string()
                    } else {
                        format!("SERVICE_{index}")
                    },
                    address: if service.service_id.is_empty() {
                        InterfaceAddress::Root
                    } else {
                        InterfaceAddress::Service(service.service_id.clone())
                    },
                });
            }
        }
        if contract.default_interface.as_ref() == Some(&reference) {
            interface_options.bindings.push(GenerateRustBinding {
                name: "DEFAULT".to_string(),
                address: InterfaceAddress::Default,
            });
        }
        for (index, binding) in contract
            .bare_interfaces
            .as_deref()
            .unwrap_or_default()
            .iter()
            .enumerate()
        {
            if binding.interface == reference {
                interface_options.bindings.push(GenerateRustBinding {
                    name: format!("BARE_{index}"),
                    address: InterfaceAddress::Bare(binding.prefix.clone()),
                });
            }
        }
        let generated = generate_rust_interface(schema, &interface_options);
        unsupported.extend(generated.unsupported);
        files.insert(format!("{file_stem}.rs"), generated.code);
        module_source.push_str(&format!("pub mod {module};\n"));
        modules.insert(reference, module);
    }
    files.insert("mod.rs".to_string(), module_source);
    Ok(GeneratedRustContract {
        files,
        modules,
        unsupported,
    })
}
